# Generated by Django 2.0.2 on 2018-05-13 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Author', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Category', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='book',
            name='epoch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Epoch', verbose_name='时代'),
        ),
        migrations.AddField(
            model_name='book',
            name='languagekind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.LanguageKind', verbose_name='语种'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='books.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Chapter', verbose_name='所属章节'),
        ),
        migrations.CreateModel(
            name='BannerBook',
            fields=[
            ],
            options={
                'verbose_name': '轮播图书',
                'verbose_name_plural': '轮播图书',
                'proxy': True,
                'indexes': [],
            },
            bases=('books.book',),
        ),
    ]
