# Generated by Django 2.0.2 on 2018-05-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180514_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='wordcount',
            field=models.IntegerField(blank=True, default=0, verbose_name='文章字数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='wordcount',
            field=models.IntegerField(blank=True, default=0, verbose_name='总字数'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='wordcount',
            field=models.IntegerField(blank=True, default=0, verbose_name='章节字数'),
        ),
    ]
