# Generated by Django 2.0.2 on 2018-05-13 18:14

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='作者名字')),
                ('workyears', models.IntegerField(default=0, verbose_name='写作年限')),
                ('features', models.CharField(max_length=50, verbose_name='写作风格')),
                ('clicknums', models.IntegerField(default=0, verbose_name='点击数')),
                ('favnums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('image', models.ImageField(default='', max_length=256, upload_to='author/%Y/%m', verbose_name='头像')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='出版社名字')),
                ('category', models.CharField(choices=[('gy', '国有'), ('sy', '私有'), ('hz', '合资'), ('dz', '独资'), ('gfz', '股份制')], default='gy', max_length=3, verbose_name='机构类型')),
                ('abstract', models.CharField(blank=True, default='该机构很赖，没有写简介信息', max_length=150, verbose_name='机构简介')),
                ('desc', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='出版社介绍\t')),
                ('clicknums', models.IntegerField(default=0, verbose_name='点击数')),
                ('favnums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('starnums', models.IntegerField(default=0, verbose_name='星级数')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publisher/%Y/%m', verbose_name='出版社标志')),
                ('address', models.CharField(max_length=150, verbose_name='出版社地址')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Publisher', verbose_name='签约出版社'),
        ),
    ]
